// Code generated by topics-generator - DO NOT EDIT.
// This file is generated and any manual changes will be lost.
package contract_router

const AccessManagerUpdatedSignature = "AccessManagerUpdated(address)"
const AccessManagerUpdatedTopic = "0xa5bc17e575e3b53b23d0e93e121a5a66d1de4d5edb4dfde6027b14d79b7f2b9c"
const AdminChangedSignature = "AdminChanged(address,address)"
const AdminChangedTopic = "0x7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f"
const BeaconUpgradedSignature = "BeaconUpgraded(address)"
const BeaconUpgradedTopic = "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e"
const RoutingUpdatedSignature = "RoutingUpdated(bytes4,address,bool,bool)"
const RoutingUpdatedTopic = "0xd7732b31e65a6e584dd5881f392ef25ab0b38bdd0b2fb55641e4be90d4dd4f9a"
const UpgradedSignature = "Upgraded(address)"
const UpgradedTopic = "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b"
