// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SendAlertsReader is a Reader for the SendAlerts structure.
type SendAlertsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendAlertsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendAlertsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSendAlertsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSendAlertsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewSendAlertsBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSendAlertsOK creates a SendAlertsOK with default headers values
func NewSendAlertsOK() *SendAlertsOK {
	return &SendAlertsOK{}
}

/* SendAlertsOK describes a response with status code 200, with default header values.

Successfully sent alerts
*/
type SendAlertsOK struct {
}

func (o *SendAlertsOK) Error() string {
	return fmt.Sprintf("[POST /alerts][%d] sendAlertsOK ", 200)
}

func (o *SendAlertsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendAlertsBadRequest creates a SendAlertsBadRequest with default headers values
func NewSendAlertsBadRequest() *SendAlertsBadRequest {
	return &SendAlertsBadRequest{}
}

/* SendAlertsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SendAlertsBadRequest struct {
	Payload *SendAlertsBadRequestBody
}

func (o *SendAlertsBadRequest) Error() string {
	return fmt.Sprintf("[POST /alerts][%d] sendAlertsBadRequest  %+v", 400, o.Payload)
}
func (o *SendAlertsBadRequest) GetPayload() *SendAlertsBadRequestBody {
	return o.Payload
}

func (o *SendAlertsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SendAlertsBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSendAlertsInternalServerError creates a SendAlertsInternalServerError with default headers values
func NewSendAlertsInternalServerError() *SendAlertsInternalServerError {
	return &SendAlertsInternalServerError{}
}

/* SendAlertsInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type SendAlertsInternalServerError struct {
}

func (o *SendAlertsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /alerts][%d] sendAlertsInternalServerError ", 500)
}

func (o *SendAlertsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendAlertsBadGateway creates a SendAlertsBadGateway with default headers values
func NewSendAlertsBadGateway() *SendAlertsBadGateway {
	return &SendAlertsBadGateway{}
}

/* SendAlertsBadGateway describes a response with status code 502, with default header values.

Bad gateway
*/
type SendAlertsBadGateway struct {
}

func (o *SendAlertsBadGateway) Error() string {
	return fmt.Sprintf("[POST /alerts][%d] sendAlertsBadGateway ", 502)
}

func (o *SendAlertsBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*SendAlertsBadRequestBody send alerts bad request body
swagger:model SendAlertsBadRequestBody
*/
type SendAlertsBadRequestBody struct {

	// reason
	Reason string `json:"reason,omitempty"`
}

// Validate validates this send alerts bad request body
func (o *SendAlertsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send alerts bad request body based on context it is used
func (o *SendAlertsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendAlertsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendAlertsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res SendAlertsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
