// Code generated by topics-generator - DO NOT EDIT.
// This file is generated and any manual changes will be lost.
package contract_access_manager

const AdminChangedSignature = "AdminChanged(address,address)"
const AdminChangedTopic = "0x7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f"
const BeaconUpgradedSignature = "BeaconUpgraded(address)"
const BeaconUpgradedTopic = "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e"
const RoleAdminChangedSignature = "RoleAdminChanged(bytes32,bytes32,bytes32)"
const RoleAdminChangedTopic = "0xbd79b86ffe0ab8e8776151514217cd7cacd52c909f66475c3af44e129f0b00ff"
const RoleGrantedSignature = "RoleGranted(bytes32,address,address)"
const RoleGrantedTopic = "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d"
const RoleRevokedSignature = "RoleRevoked(bytes32,address,address)"
const RoleRevokedTopic = "0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b"
const UpgradedSignature = "Upgraded(address)"
const UpgradedTopic = "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b"
