// Code generated by topics-generator - DO NOT EDIT.
// This file is generated and any manual changes will be lost.
package contract_forta

const AdminChangedSignature = "AdminChanged(address,address)"
const AdminChangedTopic = "0x7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f"
const ApprovalSignature = "Approval(address,address,uint256)"
const ApprovalTopic = "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
const BeaconUpgradedSignature = "BeaconUpgraded(address)"
const BeaconUpgradedTopic = "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e"
const DelegateChangedSignature = "DelegateChanged(address,address,address)"
const DelegateChangedTopic = "0x3134e8a2e6d97e929a7e54011ea5485d7d196dd5f0ba4d4ef95803e8e3fc257f"
const DelegateVotesChangedSignature = "DelegateVotesChanged(address,uint256,uint256)"
const DelegateVotesChangedTopic = "0xdec2bacdd2f05b59de34da9b523dff8be42e5e38e818c82fdb0bae774387a724"
const RoleAdminChangedSignature = "RoleAdminChanged(bytes32,bytes32,bytes32)"
const RoleAdminChangedTopic = "0xbd79b86ffe0ab8e8776151514217cd7cacd52c909f66475c3af44e129f0b00ff"
const RoleGrantedSignature = "RoleGranted(bytes32,address,address)"
const RoleGrantedTopic = "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d"
const RoleRevokedSignature = "RoleRevoked(bytes32,address,address)"
const RoleRevokedTopic = "0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b"
const TransferSignature = "Transfer(address,address,uint256)"
const TransferTopic = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
const UpgradedSignature = "Upgraded(address)"
const UpgradedTopic = "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b"
