// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: alert_stream.proto

package protocol

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriptions []*CombinerBotSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *AlertStreamRequest) Reset() {
	*x = AlertStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertStreamRequest) ProtoMessage() {}

func (x *AlertStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertStreamRequest.ProtoReflect.Descriptor instead.
func (*AlertStreamRequest) Descriptor() ([]byte, []int) {
	return file_alert_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AlertStreamRequest) GetSubscriptions() []*CombinerBotSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type AlertStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alert *AlertEvent `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
}

func (x *AlertStreamResponse) Reset() {
	*x = AlertStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertStreamResponse) ProtoMessage() {}

func (x *AlertStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertStreamResponse.ProtoReflect.Descriptor instead.
func (*AlertStreamResponse) Descriptor() ([]byte, []int) {
	return file_alert_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AlertStreamResponse) GetAlert() *AlertEvent {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_alert_stream_proto protoreflect.FileDescriptor

var file_alert_stream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x66, 0x6f,
	0x72, 0x74, 0x61, 0x1a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0b, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a,
	0x12, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69,
	0x6e, 0x65, 0x72, 0x42, 0x6f, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x46, 0x0a, 0x13, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x61, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x32, 0x6c, 0x0a, 0x12, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x56, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x21, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x61, 0x2e, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x61, 0x2e,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x00, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_alert_stream_proto_rawDescOnce sync.Once
	file_alert_stream_proto_rawDescData = file_alert_stream_proto_rawDesc
)

func file_alert_stream_proto_rawDescGZIP() []byte {
	file_alert_stream_proto_rawDescOnce.Do(func() {
		file_alert_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_stream_proto_rawDescData)
	})
	return file_alert_stream_proto_rawDescData
}

var file_alert_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alert_stream_proto_goTypes = []interface{}{
	(*AlertStreamRequest)(nil),      // 0: network.forta.AlertStreamRequest
	(*AlertStreamResponse)(nil),     // 1: network.forta.AlertStreamResponse
	(*CombinerBotSubscription)(nil), // 2: network.forta.CombinerBotSubscription
	(*AlertEvent)(nil),              // 3: network.forta.AlertEvent
}
var file_alert_stream_proto_depIdxs = []int32{
	2, // 0: network.forta.AlertStreamRequest.subscriptions:type_name -> network.forta.CombinerBotSubscription
	3, // 1: network.forta.AlertStreamResponse.alert:type_name -> network.forta.AlertEvent
	0, // 2: network.forta.AlertStreamService.Subscribe:input_type -> network.forta.AlertStreamRequest
	1, // 3: network.forta.AlertStreamService.Subscribe:output_type -> network.forta.AlertStreamResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_stream_proto_init() }
func file_alert_stream_proto_init() {
	if File_alert_stream_proto != nil {
		return
	}
	file_agent_proto_init()
	file_alert_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_alert_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_stream_proto_goTypes,
		DependencyIndexes: file_alert_stream_proto_depIdxs,
		MessageInfos:      file_alert_stream_proto_msgTypes,
	}.Build()
	File_alert_stream_proto = out.File
	file_alert_stream_proto_rawDesc = nil
	file_alert_stream_proto_goTypes = nil
	file_alert_stream_proto_depIdxs = nil
}
