// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressBloomFilter address bloom filter
//
// swagger:model AddressBloomFilter
type AddressBloomFilter struct {

	// bitset
	// Example: AAAAAAAAACwAAAAAAAAACwAAAAAAAAAsAAALo5gpbbc=
	Bitset string `json:"bitset,omitempty"`

	// Snake case due to compatibility reasons
	// Example: 1
	ItemCount int64 `json:"item_count,omitempty"`

	// k
	// Example: 11
	K int64 `json:"k,omitempty"`

	// m
	// Example: 44
	M int64 `json:"m,omitempty"`
}

// Validate validates this address bloom filter
func (m *AddressBloomFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this address bloom filter based on context it is used
func (m *AddressBloomFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressBloomFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressBloomFilter) UnmarshalBinary(b []byte) error {
	var res AddressBloomFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
