// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AlertLabel alert label
//
// swagger:model AlertLabel
type AlertLabel struct {

	// confidence
	// Example: 0.9
	Confidence float64 `json:"confidence,omitempty"`

	// entity
	// Example: 0x113b7cc6b42105dcb8cbfe576590cf7bbc7a12f1
	Entity string `json:"entity,omitempty"`

	// entity type
	// Example: ADDRESS
	EntityType string `json:"entityType,omitempty"`

	// Label name/identifier
	// Example: scammer-eoa
	Label string `json:"label,omitempty"`

	// An associative array of string values
	// Example: {"contractAddress":"0x98883145049dec03c00cb7708cbc938058802520","operator":"0x1fFa3471A45C22B1284fE5a251eD74F40580a1E3"}
	Metadata interface{} `json:"metadata,omitempty"`

	// remove
	Remove bool `json:"remove,omitempty"`
}

// Validate validates this alert label
func (m *AlertLabel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this alert label based on context it is used
func (m *AlertLabel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AlertLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertLabel) UnmarshalBinary(b []byte) error {
	var res AlertLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
