// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SourceTransaction source transaction
//
// swagger:model SourceTransaction
type SourceTransaction struct {

	// chain Id
	ChainID int64 `json:"chainId,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`
}

// Validate validates this source transaction
func (m *SourceTransaction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this source transaction based on context it is used
func (m *SourceTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SourceTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SourceTransaction) UnmarshalBinary(b []byte) error {
	var res SourceTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
