// Code generated by topics-generator - DO NOT EDIT.
// This file is generated and any manual changes will be lost.
package contract_scanner_node_version

const AccessManagerUpdatedSignature = "AccessManagerUpdated(address)"
const AccessManagerUpdatedTopic = "0xa5bc17e575e3b53b23d0e93e121a5a66d1de4d5edb4dfde6027b14d79b7f2b9c"
const AdminChangedSignature = "AdminChanged(address,address)"
const AdminChangedTopic = "0x7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f"
const BeaconUpgradedSignature = "BeaconUpgraded(address)"
const BeaconUpgradedTopic = "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e"
const RouterUpdatedSignature = "RouterUpdated(address)"
const RouterUpdatedTopic = "0x7aed1d3e8155a07ccf395e44ea3109a0e2d6c9b29bbbe9f142d9790596f4dc80"
const ScannerNodeBetaVersionUpdatedSignature = "ScannerNodeBetaVersionUpdated(string,string)"
const ScannerNodeBetaVersionUpdatedTopic = "0xe5ac27c9fd9eefb9d9fd2b0878923cf7d44e611ead66cf80b7ccf184ac2927c0"
const ScannerNodeVersionUpdatedSignature = "ScannerNodeVersionUpdated(string,string)"
const ScannerNodeVersionUpdatedTopic = "0xaa8f23ad4857a5d22df0189ebc6150d51b3152d8c621c3e8d24c66387897819b"
const UpgradedSignature = "Upgraded(address)"
const UpgradedTopic = "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b"
