#!/bin/sh

CONTRACT_REPO_NAME="$1"
CONTRACT_REPO_PARENT_DIR="$2"
CONTRACT_NAME_TITLE_CASE="$3"
CONTRACT_NAME_SNAKE_CASE="$4"
FLAGS="$5"

PACKAGE_NAME_SNAKE_CASE="contract_$CONTRACT_NAME_SNAKE_CASE"
CONTRACT_PACKAGE_PATH="contracts/$PACKAGE_NAME_SNAKE_CASE"

mkdir -p $CONTRACT_PACKAGE_PATH

# copy in the ABI from local contracts repo
CONTRACT_REPO_ABI_PATH="$CONTRACT_REPO_NAME/.abis-no-errors/contracts/$CONTRACT_REPO_PARENT_DIR/$CONTRACT_NAME_TITLE_CASE.json"
CURRENT_REPO_ABI_PATH="$CONTRACT_PACKAGE_PATH/$CONTRACT_NAME_TITLE_CASE.json"
jq -M . <  "$CONTRACT_REPO_ABI_PATH" > "$CURRENT_REPO_ABI_PATH"

# copy in the contract binary from local contracts repo
CONTRACT_REPO_BIN_PATH="$CONTRACT_REPO_NAME/artifacts/contracts/$CONTRACT_REPO_PARENT_DIR/$CONTRACT_NAME_TITLE_CASE.json"
CURRENT_REPO_BIN_PATH="$CONTRACT_PACKAGE_PATH/$CONTRACT_NAME_TITLE_CASE.bin"
jq -rM '.bytecode' <  "$CONTRACT_REPO_BIN_PATH" > "$CURRENT_REPO_BIN_PATH"

abigen --out "$CONTRACT_PACKAGE_PATH/$CONTRACT_NAME_SNAKE_CASE.go" \
	--pkg "$PACKAGE_NAME_SNAKE_CASE" \
	--type "$CONTRACT_NAME_TITLE_CASE" \
	$FLAGS \
	--abi "$CURRENT_REPO_ABI_PATH" \
	--bin "$CURRENT_REPO_BIN_PATH"

go run ./scripts/topics-generator/main.go ./$CURRENT_REPO_ABI_PATH
