// Code generated by MockGen. DO NOT EDIT.
// Source: manifest/client.go

// Package mock_manifest is a generated GoMock package.
package mock_manifest

import (
	context "context"
	reflect "reflect"

	manifest "github.com/forta-network/forta-core-go/manifest"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAgentManifest mocks base method.
func (m *MockClient) GetAgentManifest(ctx context.Context, reference string) (*manifest.SignedAgentManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentManifest", ctx, reference)
	ret0, _ := ret[0].(*manifest.SignedAgentManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentManifest indicates an expected call of GetAgentManifest.
func (mr *MockClientMockRecorder) GetAgentManifest(ctx, reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentManifest", reflect.TypeOf((*MockClient)(nil).GetAgentManifest), ctx, reference)
}
